services:
  - type: web
    name: taste-and-grow-api
    env: docker
    region: frankfurt  # Change to your preferred region (oregon, frankfurt, singapore, etc.)
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: DIRECT_URL
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true  # Automatically generates a secure secret

